### ISSUE TITLE
pip cannot install package

### ISSUE THREAD

**Issue by ShixiangWang** [dztall/ccr_bugs#5]
Mobile C Shell 1.0.0
Type 'help' to see available commands.

示例代码 13> pip install loon
ERROR: Exception:
Traceback (most recent call last):
  File "~/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "~/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "~/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "~/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "~/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 311, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, self.require_hashes)
  File "~/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 225, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "~/lib/python3.7/site-packages/pip/_internal/index.py", line 879, in find_requirement
    req.name, specifier=req.specifier, hashes=hashes,
  File "~/lib/python3.7/site-packages/pip/_internal/index.py", line 861, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "~/lib/python3.7/site-packages/pip/_internal/index.py", line 791, in find_all_candidates
    collected_links = self._link_collector.collect_links(project_name)
  File "~/lib/python3.7/site-packages/pip/_internal/collector.py", line 541, in collect_links
    for page in self._get_pages(url_locations):
  File "~/lib/python3.7/site-packages/pip/_internal/collector.py", line 493, in _get_pages
    page = _get_html_page(location, session=self.session)
  File "~/lib/python3.7/site-packages/pip/_internal/collector.py", line 339, in _get_html_page
    resp = _get_html_response(url, session=session)
  File "~/lib/python3.7/site-packages/pip/_internal/collector.py", line 146, in _get_html_response
    "Cache-Control": "max-age=0",
  File "~/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "~/lib/python3.7/site-packages/pip/_internal/network/session.py", line 426, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "~/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "~/lib/python3.7/site-packages/pip/_vendor/requests/sessions.py", line 686, in send
    r.content
  File "~/lib/python3.7/site-packages/pip/_vendor/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "~/lib/python3.7/site-packages/pip/_vendor/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "~/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "~/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "~/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 65, in read
    self._close()
  File "~/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 52, in _close
    self.__callback(self.__buf.getvalue())
  File "~/lib/python3.7/site-packages/pip/_vendor/cachecontrol/controller.py", line 300, in cache_response
    cache_url, self.serializer.dumps(request, response, body=body)
  File "~/lib/python3.7/site-packages/pip/_internal/network/cache.py", line 67, in set
    f.write(value)
  File "~/Python3/Lib/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "~/lib/python3.7/site-packages/pip/_internal/utils/filesystem.py", line 99, in adjacent_tmp_file
    os.fsync(result.file.fileno())
AttributeError: module 'os' has no attribute 'fsync'
示例代码 13>

**Comment by dztall** [comment]
Maybe need to support fsync in mobile C python runtime.

**Comment by ShixiangWang** [comment]
How to do this?

**Comment by Apuchandmalik** [comment]
Same here,I also unable to install python modules like bs4

**Comment by Skonikol** [comment]
> How to do this?

Have you solved the problem with installing pip ?
